name: Build Windows Docker image

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@v1

    - name: Build docker image
      run: |
        docker build -t myimage -f gh-runner-win/Dockerfile gh-runner-win --build-arg RUNNER_VERSION=2.278.0
    
    